var searchData=
[
  ['object',['Object',['../classosmium_1_1Object.html',1,'osmium']]],
  ['object_5fequal_5ftype_5fid',['object_equal_type_id',['../structosmium_1_1osm_1_1object__equal__type__id.html',1,'osmium::osm']]],
  ['object_5fequal_5ftype_5fid_5fversion',['object_equal_type_id_version',['../structosmium_1_1osm_1_1object__equal__type__id__version.html',1,'osmium::osm']]],
  ['object_5forder_5ftype_5fid_5freverse_5fversion',['object_order_type_id_reverse_version',['../structosmium_1_1osm_1_1object__order__type__id__reverse__version.html',1,'osmium::osm']]],
  ['object_5forder_5ftype_5fid_5fversion',['object_order_type_id_version',['../structosmium_1_1osm_1_1object__order__type__id__version.html',1,'osmium::osm']]],
  ['objectbuilder',['ObjectBuilder',['../classosmium_1_1memory_1_1ObjectBuilder.html',1,'osmium::memory']]],
  ['objectbuilder_3c_20relationmemberlist_20_3e',['ObjectBuilder&lt; RelationMemberList &gt;',['../classosmium_1_1memory_1_1ObjectBuilder.html',1,'osmium::memory']]],
  ['objectbuilder_3c_20taglist_20_3e',['ObjectBuilder&lt; TagList &gt;',['../classosmium_1_1memory_1_1ObjectBuilder.html',1,'osmium::memory']]],
  ['objectbuilder_3c_20waynodelist_20_3e',['ObjectBuilder&lt; WayNodeList &gt;',['../classosmium_1_1memory_1_1ObjectBuilder.html',1,'osmium::memory']]],
  ['objectpointercollection',['ObjectPointerCollection',['../classosmium_1_1osm_1_1ObjectPointerCollection.html',1,'osmium::osm']]],
  ['objectrelations',['ObjectRelations',['../classosmium_1_1handler_1_1ObjectRelations.html',1,'osmium::handler']]],
  ['ogr_5ffactory_5ftraits',['ogr_factory_traits',['../structosmium_1_1geom_1_1ogr__factory__traits.html',1,'osmium::geom']]],
  ['ogrfactory',['OGRFactory',['../classosmium_1_1geom_1_1OGRFactory.html',1,'osmium::geom']]],
  ['oploutputblock',['OPLOutputBlock',['../classosmium_1_1io_1_1detail_1_1OPLOutputBlock.html',1,'osmium::io::detail']]],
  ['oploutputformat',['OPLOutputFormat',['../classosmium_1_1io_1_1detail_1_1OPLOutputFormat.html',1,'osmium::io::detail']]],
  ['options',['Options',['../classosmium_1_1util_1_1Options.html',1,'osmium::util']]],
  ['osmentity',['OSMEntity',['../classosmium_1_1OSMEntity.html',1,'osmium']]],
  ['osmobjectbuilder',['OSMObjectBuilder',['../classosmium_1_1osm_1_1OSMObjectBuilder.html',1,'osmium::osm']]],
  ['outputformat',['OutputFormat',['../classosmium_1_1io_1_1detail_1_1OutputFormat.html',1,'osmium::io::detail']]],
  ['outputformatfactory',['OutputFormatFactory',['../classosmium_1_1io_1_1detail_1_1OutputFormatFactory.html',1,'osmium::io::detail']]],
  ['outputiterator',['OutputIterator',['../classosmium_1_1io_1_1OutputIterator.html',1,'osmium::io']]],
  ['outputthread',['OutputThread',['../classosmium_1_1io_1_1OutputThread.html',1,'osmium::io']]]
];
